### ISSUE TITLE
Exact test for Equivalence of binomial proportion

### ISSUE THREAD

**Issue by MunjalP** [heliosdrm/pwr#1]
How can one find the Exact power test for binomial proportion.for e.g i have to use the SAS in this case i can do this in following way.
proc power;
onesamplefreq test = equiv_exact
alpha = 0.05
proportion = 0.30
lower = 0.2
upper = 0.4
ntotal = 500
power = .;
run;
But using pwr package can i get the similar result ? how ?
Thank you

**Comment by heliosdrm** [comment]
Perhaps you may want to check `pwr.p.test`.

However, I don't know if the algorithm used by SAS will be the same as Cohen's (arcsine transformation of the proportion).
