### ISSUE TITLE
ChangeLog --> NEWS?

### ISSUE THREAD

**Issue by tbates** [heliosdrm/pwr#14]
This is very minor, but I wonder if the ChangeLog might not be renamed NEWS? Then it will appear in places like

    news(pack="pwr")

I've got a feeling git has subsumed the purpose of a detailed ChangeLog, but NEWS is a great way to communicate new features.

**Comment by heliosdrm** [comment]
Thanks for the suggestion. I'll change it in the next version.

**Comment by heliosdrm** [comment]
Changed in the current version in master.
