### ISSUE TITLE
pwr.t.test d=effect size

### ISSUE THREAD

**Issue by heliosdrm** [heliosdrm/pwr#16]
[By Bill Brown]

When looking at the documentation for pwr.t.test, the argument d is only defined as “effect size.”  The documentation could be improved by saying:
   d   Effect size (Cohen’s d) - difference between the means divided by the pooled SD

In the function power.t.test from the stats package, it uses delta as the true difference in means and sd as the standard deviation.  So, for someone coming from that package to the pwr package, one could see the possibility for confusion.

**Comment by usna71** [comment]
Thanks for posting this for me. /b

**Comment by heliosdrm** [comment]
Fixed in version 1.2-2
