### ISSUE TITLE
discrepancy for pwr.p.test

### ISSUE THREAD

**Issue by ghost** [heliosdrm/pwr#26]
hello, What am I missing here?:

> abs(ES.h(.1, .11))
0.0326294
> power.prop.test(p1 = .1, p2 = .11, sig.level = .1, power = .9)
     Two-sample comparison of proportions power calculation 

              n = 16093.88
             p1 = 0.1
             p2 = 0.11
      sig.level = 0.1
          power = 0.9
    alternative = two.sided

NOTE: n is number in *each* group

> pwr.p.test(h = ES.h(.1, .11), sig.level = .1, power = .9)

     proportion power calculation for binomial distribution (arcsine transformation) 

              h = 0.0326294
              n = 8043.529
      sig.level = 0.1
          power = 0.9
    alternative = two.sided

I validated with my own custom function and stats::power.prop.test is the right answer.
Is this a bug or am I wrong somewhere?

**Comment by heliosdrm** [comment]
`power.prop.test` is "Power Calculations for Two-Sample Test for Proportions", whereas `pwr.p.test` is "Power calculations for proportion tests (one sample)". You should compare with `pwr.2p.test`:

```R
> pwr.2p.test(h=ES.h(0.1,0.11), sig.level = .1, power = .9)
```
```
     Difference of proportion power calculation for binomial distribution (arcsine transformation) 

              h = 0.0326294
              n = 16087.06
      sig.level = 0.1
          power = 0.9
    alternative = two.sided

NOTE: same sample sizes
```

**Comment by ghost** [comment]
oopsy
i turned out a newbie

sry
