### ISSUE TITLE
Too much power?

### ISSUE THREAD

**Issue by vnckppl** [heliosdrm/pwr#27]
`pwr.anova.test(k = 2, f = 0.7, sig.level = .05, power = 0.1)
`
results in:

```
Error in uniroot(function(n) eval(p.body) - power, c(2 + 1e-10, 1e+09)) : 
  f() values at end points not of opposite sign
```

Is this a feature or a bug?

**Comment by heliosdrm** [comment]
It is expected. As noted in the documentation: "'uniroot' is used to solve power equation for unknowns, so you may see errors from it, notably about inability to bracket the root when invalid arguments are given." `power = 0.1` is an unusual parameter, and falls outside the given limits for `uniroot`.

**Comment by vnckppl** [comment]
Thank you for your feedback!
