### ISSUE TITLE
Expand repository metadata

### ISSUE THREAD

**Issue by jemus42** [heliosdrm/pwr#3]
I just found out today that this package is on GitHub as well, I've been using it for a while now.  

A few things I expected to find here:
- CRAN badge displaying current version to link back to CRAN, as per [r-pkg.org](http://r-pkg.org/services#badges)
- NEWS.md file detailing recent changes (I just updated the package without knowing what to look for / expect)

Maybe these things could be added :)

**Comment by heliosdrm** [comment]
Thanks for the hint on METACRAN and the CRAN badge. I'll have a look at it.

With respect to NEWS.md, there is the ChangeLog file. Is not that sufficient?
