### ISSUE TITLE
Why does pwr.2p.test give different sample sizes than GPower and stats::power.prop.test?

### ISSUE THREAD

**Issue by deschen1** [heliosdrm/pwr#31]
```
library(pwr)
pwr::pwr.2p.test(h = ES.h(0.022,0.001), sig.level = 0.05, power = 0.8, alternative = "greater")
```

gives:

```
     Difference of proportion power calculation for binomial distribution (arcsine transformation) 

              h = 0.2344905
              n = 224.8784
      sig.level = 0.05
          power = 0.8
    alternative = greater

NOTE: same sample sizes
```

But

`stats::power.prop.test(p1 = 0.022, p2 = 0.001, sig.level = 0.05, power = 0.8, alternative = "one.sided")`

gives:

```
     Two-sample comparison of proportions power calculation 

              n = 317.6901
             p1 = 0.022
             p2 = 0.001
      sig.level = 0.05
          power = 0.8
    alternative = one.sided

NOTE: n is number in *each* group
```

which btw is exactly the same result as obtained by GPower.

![grafik](https://user-images.githubusercontent.com/25662795/125355139-f2857780-e364-11eb-979a-410de786a45e.png)

Any ideas, what's going on here?

**Comment by deschen1** [comment]
The difference seems to come from the arsin transformation to calculate effect size h. Using the same feature in GPower yields the same results as in pwr.

**Comment by heliosdrm** [comment]
That's right. Thanks for investigating it yourself. Since it's solved, I'll close this issue.
