### ISSUE TITLE
 2 sample t test power - different sizes & different variances.

### ISSUE THREAD

**Issue by nipnipj** [heliosdrm/pwr#32]
What would be the correct command within PWR package to perform a two independent samples t power test with different sizes and different variance. Particularly, what's the correct formula to calculate "d"?

```
pwr.t2n.test(
  d=d,
  n1=n1,
  n2=n2,
  sig.level=0.05,
  alternative="two.sided")
```

**Comment by heliosdrm** [comment]
As indicated in the manual (https://cran.r-project.org/web/packages/pwr/pwr.pdf#page.18): `d` is Cohen’s *d* - difference between the means divided by the pooled standard deviation. Please read Cohen's book for further theoretical questions, which are not strictly related to the implementation of its methods in this package. Thanks.
